force-app/main/default/objects/School__c/School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>St-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <label>Student Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StudentInformationService.cls
@RestResource(urlMapping='/studentsInfo/*')
global class StudentInformationService 
{
    global class StudentInfo
    {
        String studentName{get;set;}
        String studentAddress{get;set;}
        String studentPhone{get;set;}
        String SchoolName{get;set;}
    }
    
    @httpGet
    global static StudentInfo getStudent()
    {
        RestRequest request=RestContext.Request;
        String studentId=request.requestURI.substring(request.RequestURI.lastIndexof('/')+1);
        
        Student__c student=[SELECT Id,Address__c,Student_Name__c,Phone_Number__c,school__r.Name from Student__c where Id=:studentId];
        
        StudentInfo stdInfo = new StudentInfo();
        stdInfo.studentName=student.Student_Name__c;
        stdInfo.studentAddress=student.Address__c;
        stdInfo.studentPhone=student.Phone_number__c;
        stdInfo.SchoolName=student.school__r.Name;
        
        return stdInfo;
    }
}