force-app/main/default/objects/Relational_Accounts__c/Relational_Accounts__c.object-meta.xml
<CustomObject>
    <label>Relational Accounts</label>
    <nameField>
        <label>Relational Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relational Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relational_Accounts__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relational Accounts</relationshipLabel>
    <relationshipName>Relational_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountController.cls
public with sharing class AccountController {
    @AuraEnabled(cacheable=true)
    public static List<Account> getRelatedAccounts(Id contactId) {
        // Fetch related accounts based on the Contact's current AccountId or logic
        Contact contact = [SELECT AccountId FROM Contact WHERE Id = :contactId LIMIT 1];
        List<Relational_Accounts__c> RelationalAcc = [Select id, name, Parent_Account__c, Parent_Account__r.Name from Relational_Accounts__c WHERE Parent_Account__c =:contact.AccountId];
        List<Id> AccountIds = new List<Id>();

        for(Relational_Accounts__c RA : RelationalAcc) {
            System.debug('RA Name: ' + RA.Parent_Account__c);
            AccountIds.add(RA.Parent_Account__c);
        }

        System.debug('AccountIds: ' + AccountIds);
        return [SELECT Id, Name 
                FROM Account 
                WHERE ParentId = :AccountIds OR Id = :AccountIds];
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getAccountsBySearch(String searchKey) {
        return [
            SELECT Id, Name 
            FROM Account 
            WHERE Name LIKE :('%' + searchKey + '%') 
            LIMIT 10
        ];
    }
}