force-app/main/default/objects/Dog_Facts__c/Dog_Facts__c.object-meta.xml
<CustomObject>
    <label>Dog Facts</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dog Facts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog_Facts__c/fields/bred_for__c.field-meta.xml
<CustomField>
    <fullName>bred_for__c</fullName>
    <label>bred_for</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog_Facts__c/fields/breed_group__c.field-meta.xml
<CustomField>
    <fullName>breed_group__c</fullName>
    <label>breed_group</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog_Facts__c/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <label>id</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dog_Facts__c/fields/life_span__c.field-meta.xml
<CustomField>
    <fullName>life_span__c</fullName>
    <label>life_span</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog_Facts__c/fields/origin__c.field-meta.xml
<CustomField>
    <fullName>origin__c</fullName>
    <label>origin</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog_Facts__c/fields/reference_image_id__c.field-meta.xml
<CustomField>
    <fullName>reference_image_id__c</fullName>
    <label>reference_image_id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog_Facts__c/fields/temperament__c.field-meta.xml
<CustomField>
    <fullName>temperament__c</fullName>
    <label>temperament</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DogAPIController.cls
public class DogAPIController {
    
    @InvocableMethod(label='Get dog' description='Iterates')
    public static void getDogFacts(list<EnrolmentsRequest> Name) {
        String apiUrl = 'https://api.thedogapi.com/v1/breeds';
        
        //request
        HttpRequest request = new HttpRequest();
        request.setEndpoint(apiUrl);
        request.setMethod('GET');
        
   		//response
        Http http = new Http();
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200) {
            String responseBody = response.getBody();
            list<Items> deserializeditems = (list<Items>)JSON.deserialize(responseBody, list<Items>.class);
            
            List<Dog_Facts__c> alldogsGroups= new List<Dog_Facts__c>();
   			system.debug('deserializeditems-->: '+deserializeditems.size());
            for(Items deserializeditem:deserializeditems){
                Dog_Facts__c newItem = new Dog_Facts__c();
                EnrolmentsRequest Names = new EnrolmentsRequest();
                newItem.id__c = deserializeditem.id;
                //newItem.First_Name__c = Names.FirstName;
                //system.debug('newItem.First_Name__c-->: '+newItem.First_Name__c);
                //newItem.Last_Name__c  = Names.LastName;
                newItem.name = deserializeditem.Name;
                newItem.bred_for__c = deserializeditem.bred_for;
                newItem.breed_group__c = deserializeditem.breed_group;
                newItem.life_span__c = deserializeditem.life_span;
                newItem.temperament__c = deserializeditem.temperament;
                newItem.origin__c = deserializeditem.origin;
                newItem.reference_image_id__c = deserializeditem.reference_image_id;
                alldogsGroups.add(newItem);
            }
            Database.insert(alldogsGroups);
        	}
    }
    
    public DogAPIController() {}
    public class Items {
        public integer id {get;set;}
        public String name {get;set;}
        public String bred_for {get;set;}
        public String breed_group {get;set;}
        public String life_span {get;set;}
        public String temperament {get;set;}
        public String origin {get;set;}
        public String reference_image_id {get;set;}
    }
    
    public class EnrolmentsRequest{
        @InvocableVariable
        public String FirstName;
        @InvocableVariable
        public String LastName;
    }
}