force-app/main/default/objects/Books__c/Books__c.object-meta.xml
<CustomObject>
    <label>Books</label>
    <nameField>
        <label>Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Books__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <label>Average Rating</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/Binding__c.field-meta.xml
<CustomField>
    <fullName>Binding__c</fullName>
    <label>Binding</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/Goodreads_Id__c.field-meta.xml
<CustomField>
    <fullName>Goodreads_Id__c</fullName>
    <label>Goodreads Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/image_url__c.field-meta.xml
<CustomField>
    <fullName>image_url__c</fullName>
    <label>image_url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/ISBN13__c.field-meta.xml
<CustomField>
    <fullName>ISBN13__c</fullName>
    <label>ISBN13</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <label>ISBN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/Number_of_Pages__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pages__c</fullName>
    <label>Number of Pages</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Book titlee</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/Year_Published__c.field-meta.xml
<CustomField>
    <fullName>Year_Published__c</fullName>
    <label>Year Published</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/booksSearchController.cls
public with sharing class booksSearchController {
    public booksSearchController() {

    }    
    
    @AuraEnabled(cacheable=true)
    public static List<Books__c> getBooksfrom(string bookTitle){
        String Keystring = '%' +bookTitle+ '%';
        system.debug('bookTitle---->'+Keystring);
        return [Select Id,Title__c,image_url__c,Author__c,Publisher__c, ISBN13__c,ISBN__c, Year_Published__c,Binding__c, Number_of_Pages__c,Goodreads_Id__c, Average_Rating__c from Books__c  where Title__c like:Keystring];
    }

    @AuraEnabled(cacheable=true)
    public static SearchBookEntity getbooks(string searchRecord){
            string SearchKey = searchRecord;
            string url ='https://www.goodreads.com/search/index.xml?key=RVUDBa0yOL5hPLaTvrYIdw&q='+SearchKey;			
            system.debug('URL testing--->' +url);
            HttpRequest req = new HttpRequest();
            req.setMethod('GET');
            req.setEndPoint(url);        
            Http http = new Http();
            HttpResponse res = http.send(req);        
            string body = res.getBody();
            String jsonContent = XmlParser.xmlToJson(body);
            system.debug('final values:--->' +jsonContent);
            SearchBookEntity BookResults=new SearchBookEntity();
            BookResults = SearchBookEntity.parse(jsonContent);
            return BookResults;                     	
    }        
}